version: "3"

services:
  # node-build-local:
  #   build: ./nodeBuild
  web:
    # image: node-build-local
    build: ./web
    volumes:
      - ./web:/base
    #command: pwd && ls -la && nodemon -L --inspect=0.0.0.0:5858
    command: nodemon ./dist/server.js --watch --inspect=0.0.0.0:5858
    ports:
      - "8000:4200"

