version: "3"

services:
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/app'
    #command: ash -c "nodemon -L ./dist/server.js --watch ./dist/server.js --inspect=0.0.0.0:5858 & browser-sync start -c 'bs-config.js'"
    
    ports:
      - "8000:8000"
      - "5858:5858"
      - "3001:3001"
      - "8001:8001"
